# Generated by Django 4.2 on 2023-04-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
